# Generated by Django 5.2.7 on 2025-10-29 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("data_source_created", "创建数据源"),
                            ("dataset_created", "创建数据集"),
                            ("pipeline_executed", "执行处理流程"),
                            ("visualization_created", "创建可视化"),
                            ("dashboard_created", "创建看板"),
                            ("ai_model_trained", "训练AI模型"),
                            ("data_processed", "数据处理完成"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("resource_id", models.IntegerField(blank=True, null=True)),
                (
                    "resource_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "活动记录",
                "verbose_name_plural": "活动记录",
                "db_table": "activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
