# Generated by Django 5.2.7 on 2025-10-11 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="图表类型名称")),
                ("chart_library", models.CharField(max_length=50, verbose_name="图表库")),
                (
                    "configuration_template",
                    models.JSONField(default=dict, verbose_name="配置模板"),
                ),
            ],
            options={
                "verbose_name": "图表类型",
                "verbose_name_plural": "图表类型",
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="看板名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("layout_config", models.JSONField(default=dict, verbose_name="布局配置")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "看板",
                "verbose_name_plural": "看板",
            },
        ),
        migrations.CreateModel(
            name="Visualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="可视化名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("configuration", models.JSONField(default=dict, verbose_name="可视化配置")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chart_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visualization.charttype",
                        verbose_name="图表类型",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datasets.dataset",
                        verbose_name="数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "可视化",
                "verbose_name_plural": "可视化",
            },
        ),
        migrations.CreateModel(
            name="DashboardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_x", models.IntegerField(verbose_name="X位置")),
                ("position_y", models.IntegerField(verbose_name="Y位置")),
                ("width", models.IntegerField(verbose_name="宽度")),
                ("height", models.IntegerField(verbose_name="高度")),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visualization.dashboard",
                        verbose_name="看板",
                    ),
                ),
                (
                    "visualization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visualization.visualization",
                        verbose_name="可视化",
                    ),
                ),
            ],
            options={
                "verbose_name": "看板项",
                "verbose_name_plural": "看板项",
            },
        ),
        migrations.AddField(
            model_name="dashboard",
            name="visualizations",
            field=models.ManyToManyField(
                through="visualization.DashboardItem",
                to="visualization.visualization",
                verbose_name="可视化组件",
            ),
        ),
    ]
