# Generated by Django 5.2.7 on 2025-10-29 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="看板名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("layout_config", models.JSONField(default=dict, verbose_name="布局配置")),
                ("chart_configs", models.JSONField(default=list, verbose_name="图表配置")),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据看板",
                "verbose_name_plural": "数据看板",
                "db_table": "dashboards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="图表名称")),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "折线图"),
                            ("bar", "柱状图"),
                            ("pie", "饼图"),
                            ("scatter", "散点图"),
                            ("table", "表格"),
                            ("map", "地图"),
                        ],
                        max_length=50,
                        verbose_name="图表类型",
                    ),
                ),
                ("dataset_id", models.IntegerField(verbose_name="数据集ID")),
                ("config", models.JSONField(default=dict, verbose_name="图表配置")),
                ("position", models.JSONField(default=dict, verbose_name="位置配置")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "看板图表",
                "verbose_name_plural": "看板图表",
                "db_table": "dashboard_charts",
                "ordering": ["position"],
            },
        ),
    ]
