# Generated by Django 5.2.7 on 2025-10-12 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasets", "0003_datasource_error_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="处理流程名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "output_dataset_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="输出数据集名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "input_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_pipelines",
                        to="datasets.dataset",
                        verbose_name="输入数据集",
                    ),
                ),
                (
                    "output_dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_pipelines",
                        to="datasets.dataset",
                        verbose_name="输出数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "处理流程",
                "verbose_name_plural": "处理流程",
            },
        ),
        migrations.CreateModel(
            name="PipelineModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="处理模块", max_length=200, verbose_name="模块名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("filter", "数据过滤"),
                            ("transform", "数据转换"),
                            ("aggregate", "数据聚合"),
                            ("clean", "数据清洗"),
                        ],
                        max_length=20,
                        verbose_name="模块类型",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="执行顺序")),
                ("configuration", models.JSONField(default=dict, verbose_name="模块配置")),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing.processingpipeline",
                        verbose_name="处理流程",
                    ),
                ),
            ],
            options={
                "verbose_name": "流程模块",
                "verbose_name_plural": "流程模块",
                "ordering": ["order"],
            },
        ),
    ]
