# Generated by Django 5.2.7 on 2025-10-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0002_alter_pipelinemodule_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinemodule",
            name="type",
            field=models.CharField(
                choices=[
                    ("filter", "数据过滤"),
                    ("transform", "数据转换"),
                    ("aggregate", "数据聚合"),
                    ("clean", "数据清洗"),
                    ("select", "数据截取"),
                ],
                max_length=20,
                verbose_name="模块类型",
            ),
        ),
    ]
