# Generated by Django 5.2.7 on 2025-10-13 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasets", "0003_datasource_error_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模型名称")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("price_prediction", "价格预测"),
                            ("yield_prediction", "产量预测"),
                            ("disease_detection", "病害检测"),
                            ("market_analysis", "市场分析"),
                            ("climate_impact", "气候影响分析"),
                        ],
                        max_length=50,
                        verbose_name="模型类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="模型描述")),
                (
                    "version",
                    models.CharField(default="1.0", max_length=50, verbose_name="版本号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "训练中"),
                            ("active", "已激活"),
                            ("inactive", "未激活"),
                            ("error", "错误"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(blank=True, null=True, verbose_name="准确率"),
                ),
                (
                    "model_file",
                    models.FileField(blank=True, null=True, upload_to="ai_models/"),
                ),
                ("feature_columns", models.JSONField(default=list, verbose_name="特征列")),
                (
                    "target_column",
                    models.CharField(blank=True, max_length=100, verbose_name="目标列"),
                ),
                (
                    "training_config",
                    models.JSONField(default=dict, verbose_name="训练配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "training_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="datasets.dataset",
                        verbose_name="训练数据",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI模型",
                "verbose_name_plural": "AI模型",
                "db_table": "ai_models",
            },
        ),
        migrations.CreateModel(
            name="PredictionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("batch_prediction", "批量预测"),
                            ("realtime_prediction", "实时预测"),
                            ("model_training", "模型训练"),
                        ],
                        max_length=50,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "input_parameters",
                    models.JSONField(default=dict, verbose_name="输入参数"),
                ),
                (
                    "output_result",
                    models.JSONField(blank=True, null=True, verbose_name="输出结果"),
                ),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="prediction_results/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("progress", models.FloatField(default=0, verbose_name="进度")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai.aimodel",
                        verbose_name="AI模型",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "input_dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datasets.dataset",
                        verbose_name="输入数据",
                    ),
                ),
            ],
            options={
                "verbose_name": "预测任务",
                "verbose_name_plural": "预测任务",
                "db_table": "prediction_tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
